pause:
  name: pause
  description: Pause current print.
continue_print:
  name: continue_print
  description: continue current print.
abort:
  name: abort
  description: Abort current print.
get_file_names:
  name: get file names
  description: Get the files that stored in printer.
print_file:
  name: print file
  description: print file from printer
  fields:
    file_name:
      name: "file name"
      description: "Filename without /data/ prefix!"
      example: "Apos_PLA_14m16s.gcode"
