# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest

on:
  push:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Europe/Stockholm"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest-md pytest-emoji

    - uses: pavelzw/pytest-action@v2
      with:
        emoji: false
        verbose: false
        job-summary: true
